name: models4life
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.8
  mobx: ^2.3.3+2
  mobx_codegen: ^2.6.1
  flutter_mobx: ^2.2.1+1
  supabase_flutter: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/alucard.png
    - assets/dante.png
    - assets/doom_guy.jpeg
    - assets/lady_maria.jpg
    - assets/nanami.png
    - assets/obelix.jpg
    - assets/radan.jpg
    - assets/teminator.jpg
    - assets/vergil.png

  fonts:
    - family: Validex
      fonts:
        - asset: assets/validex-metallic-svg.otf

